'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ITGS_IA_Application.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abdallah_Al_Handasi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abdallah_Al_Handasi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abhishek_Warrier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abhishek_Warrier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aisha_Al_Maqbali() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aisha_Al_Maqbali", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Akram_Aykour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Akram_Aykour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alex_Watts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alex_Watts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Andee_Kirsten_Torres() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Andee_Kirsten_Torres", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Andrea_Gail_Legaspi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Andrea_Gail_Legaspi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Antonio_Alec_Gemarino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Antonio_Alec_Gemarino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aqeel_Jacobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aqeel_Jacobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Caitlyn_Gomez() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Caitlyn_Gomez", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Christine_Nolido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Christine_Nolido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Courtney_Healy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Courtney_Healy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property David_Tomalin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("David_Tomalin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eunhye_Hwang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eunhye_Hwang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fiza_Dar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fiza_Dar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floreiniel_Alfonso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floreiniel_Alfonso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gabriel_Santos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gabriel_Santos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hadeel_Al_Mamari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hadeel_Al_Mamari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hannah_Willis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hannah_Willis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Harshit_Sharma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Harshit_Sharma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hoor_Al_Ghaithi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hoor_Al_Ghaithi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Isaac_Carberry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Isaac_Carberry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ishtiaq_Jacobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ishtiaq_Jacobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Israa_Al_Maqbali() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Israa_Al_Maqbali", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jaira_Gemarino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jaira_Gemarino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jake_Marshall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jake_Marshall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jelani_Jed_Gemarino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jelani_Jed_Gemarino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Julio_Gonzalez() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Julio_Gonzalez", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kameron_Masoner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kameron_Masoner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Karen_Mathews() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Karen_Mathews", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kerry_Ann_Benjamin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kerry_Ann_Benjamin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Klint_John_Marino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Klint_John_Marino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mayar_Barakat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mayar_Barakat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Michael_Ridgway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Michael_Ridgway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nicole_Alfonso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nicole_Alfonso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Noaf_Al_Balushi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Noaf_Al_Balushi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omar_Al_Shirawi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omar_Al_Shirawi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Prishanthi_Govender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prishanthi_Govender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rafael_Vinci() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rafael_Vinci", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Saif_Al_Shibli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saif_Al_Shibli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sanna_Persterer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sanna_Persterer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sara_Barendregt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sara_Barendregt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property School_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("School_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shalin_Govender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shalin_Govender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shamma_Al_Shibli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shamma_Al_Shibli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sulaiman_Al_Saidi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sulaiman_Al_Saidi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sultan_Al_Zefeiti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sultan_Al_Zefeiti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tahlyn_Chetty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tahlyn_Chetty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taif_Al_Balushi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taif_Al_Balushi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taya_Masoner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taya_Masoner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teja_Tiriveedhi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teja_Tiriveedhi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trina_De_Vera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trina_De_Vera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trisha_Centino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trisha_Centino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wi_aam_Jacobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wi_aam_Jacobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Willem_Alberts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Willem_Alberts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Yann_Rival() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yann_Rival", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zeyad_Barakat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zeyad_Barakat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zyrelle_Queen_Marino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zyrelle_Queen_Marino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
